In [9]:
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression

random_seed = 42

ratings = pd.read_table('ml-1m/ratings.dat',  sep = '::', engine = 'python', header = None, names= ['UserID', 'MovieID', 'Rating', 'Timestamp'])


In [10]:
# Change invalid ratings to valid ones
ratings['Rating'].values[ratings['Rating'].values > 5] = 5
ratings['Rating'].values[ratings['Rating'].values < 1] = 1

In [11]:
# Create k-fold indices
kf = KFold(n_splits = 5, shuffle=True, random_state=random_seed)
for train, test in kf.split(ratings):
    print(train, test)

[      1       2       3 ... 1000205 1000207 1000208] [      0       7      12 ... 1000196 1000198 1000206]
[      0       1       2 ... 1000205 1000206 1000208] [      6       9      10 ... 1000192 1000200 1000207]
[      0       1       3 ... 1000205 1000206 1000207] [      2      11      26 ... 1000201 1000204 1000208]
[      0       2       3 ... 1000206 1000207 1000208] [      1       4      16 ... 1000175 1000193 1000199]
[      0       1       2 ... 1000206 1000207 1000208] [      3       5       8 ... 1000202 1000203 1000205]


First, we try out the three most naive methods: predicting the global average, the average of the user, or the average of the movie.

In [14]:
rmseglobalavg = []
maeglobalavg = []
rmseuseravg = []
maeuseravg = []
rmseitemavg = []
maeitemavg = []

for trainid, testid in kf.split(ratings):
    
    X_train = ratings[['UserID','MovieID']].iloc[trainid]
    X_test = ratings[['UserID','MovieID']].iloc[testid]
    y_train = ratings['Rating'].iloc[trainid]
    y_test = ratings['Rating'].iloc[testid]
    
    # define averages
    global_avg = y_train.mean()
    user_avg = ratings[['UserID','Rating']].iloc[trainid].groupby(['UserID']).mean()
    item_avg = ratings[['MovieID','Rating']].iloc[trainid].groupby(['MovieID']).mean()
 
    # create lists to put results in
    global_avg_pred = []
    user_avg_pred = []
    item_avg_pred = []
    
    # loop over test set
    for x in testid:
       
        # predict using global average
        global_avg_pred.append(global_avg)
    
        # predict using user average
        if ratings['UserID'][x] in user_avg.index.tolist():
            user_rating = user_avg.loc[ratings['UserID'][x]]
            user_avg_pred.append(user_rating[0])
        else: user_avg_pred.append(global_avg)
        
        # predict using item average
        if ratings['MovieID'][x] in item_avg.index.tolist():
            item_rating = item_avg.loc[ratings['MovieID'][x]]
            item_avg_pred.append(item_rating[0])
        else: item_avg_pred.append(global_avg)

    # append results to lists
    rmseglobalavg.append(math.sqrt(mean_squared_error(y_test, global_avg_pred)))
    maeglobalavg.append(mean_absolute_error(y_test, global_avg_pred))
    
    rmseuseravg.append(math.sqrt(mean_squared_error(y_test,user_avg_pred)))
    maeuseravg.append(mean_absolute_error(y_test, user_avg_pred))
    
    rmseitemavg.append(math.sqrt(mean_squared_error(y_test, item_avg_pred)))
    maeitemavg.append(mean_absolute_error(y_test, item_avg_pred))

# print averages of lists
print('global rmse: ', sum(rmseglobalavg)/len(rmseglobalavg))
print('global mae: ', sum(maeglobalavg)/len(maeglobalavg))
print('user rmse: ', sum(rmseuseravg)/len(rmseuseravg))
print('user mae: ', sum(maeuseravg)/len(maeuseravg))
print('item rmse: ', sum(rmseitemavg)/len(rmseitemavg))
print('item mae: ', sum(maeitemavg)/len(maeitemavg))

global rmse:  1.117101450528282
global mae:  0.9338619186570455
user rmse:  1.0354800404316435
user mae:  0.8289498348484926
item rmse:  0.9793666761448853
item mae:  0.7822841972440417


In [13]:
# lists to put results in
model1rmseavg = []
model2rmseavg = []
model1maeavg = []
model2maeavg = []

for trainid, testid in kf.split(ratings):
    
    X_train = ratings[['UserID','MovieID']].iloc[trainid]
    X_test = ratings[['UserID','MovieID']].iloc[testid]
    y_train = ratings['Rating'].iloc[trainid]
    y_test = ratings['Rating'].iloc[testid]
    
    # predict using alpha*user + beta*item
    model1 = LinearRegression(fit_intercept = False)
    model1.fit(X_train, y_train)
    pred1 = model1.predict(X_test)
    
    # predict using alpha*user + beta*item + gamma
    model2 = LinearRegression()
    model2.fit(X_train, y_train)
    pred2 = model2.predict(X_test)
    
    # compute rmse and mae
    rmse1 = math.sqrt(mean_squared_error(y_test, pred1))
    mae1 = mean_absolute_error(y_test, pred1)
    rmse2 = math.sqrt(mean_squared_error(y_test, pred2))
    mae2 = mean_absolute_error(y_test, pred2)
    
    # add results to list
    model1rmseavg.append(rmse1)
    model2rmseavg.append(rmse2)
    model1maeavg.append(mae1)
    model2maeavg.append(mae2)
    
# print averages of lists
print('model 1 rmse: ', sum(model1rmseavg)/len(model1rmseavg))
print('model 1 mae: ', sum(model1maeavg)/len(model1maeavg))
print('model 2 rmse: ', sum(model2rmseavg)/len(model2rmseavg))
print('model 2 mae: ', sum(model2maeavg)/len(model2maeavg))

model 1 rmse:  1.7776898530848342
model 1 mae:  1.4458338227929346
model 2 rmse:  1.114740675708551
model 2 mae:  0.9301613262832701
